name: Docker Build Image
description: "Action to Build the Project Docker Image"

inputs:
  path_dockerfile:
    description: "Path to Dockerfile"
  image_name:
    description: "Image name"
  tag_name:
    description: "Docker Image Tag name"

outputs:
  docker_image_name:
    description: "Built Docker Image Name"
    value: ${{ steps.set_docker_image_name.outputs.docker_image_name }}

runs:
  using: 'composite'
  steps:
    - name: Define Tag name
      run: |
        if [ -z "${{ inputs.tag_name}}" ]; then
          echo "TAG=$(date +%s)" >> $GITHUB_ENV
        else
          echo "TAG=${{ inputs.tag_name}}" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Build Docker Image
      run: docker build . --file ${{ inputs.path_dockerfile }} --tag ${{ inputs.image_name }}:${{ env.TAG }}
      shell: bash

    - name: Set output docker_image_name
      id: set_docker_image_name
      run: echo "docker_image_name=${{ inputs.image_name  }}:${{ env.TAG }}" >> $GITHUB_OUTPUT
      shell: bash