name: maven_build
author: Tales Figueiredo
description: maven_build
runs:
  using: 'composite'
  steps:
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install
      shell: bash