name: Docker Build Image
description: "Action to Build the Project Docker Image"

inputs:
  DOCKERHUB_USERNAME:
    description: "Docker UserName"
  DOCKERHUB_TOKEN:
    description: "Docker Password"
  DOCKER_IMAGE_NAME:
    description: "Docker Image Name to Push"

runs:
  using: 'composite'
  steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.DOCKERHUB_USERNAME }}
        password: ${{ inputs.DOCKERHUB_TOKEN }}

    - name: Build Docker Image
      run: docker push ${{ inputs.DOCKER_IMAGE_NAME }}
      shell: bash

